# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GatewayTimeout do
  @moduledoc """
  Gateway timeout model
  """

  @derive Jason.Encoder
  defstruct [
    :error,
    :timeout
  ]

  @type t :: %__MODULE__{
    :error => String.t,
    :timeout => integer() | nil
  }

  def decode(value) do
    value
  end
end

