# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetWarsWarIdAlly do
  @moduledoc """
  ally object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :corporation_id
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :corporation_id => integer() | nil
  }

  def decode(value) do
    value
  end
end

