# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFleetsFleetIdMembers200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :character_id,
    :join_time,
    :role,
    :role_name,
    :ship_type_id,
    :solar_system_id,
    :squad_id,
    :station_id,
    :takes_fleet_warp,
    :wing_id
  ]

  @type t :: %__MODULE__{
    :character_id => integer(),
    :join_time => DateTime.t,
    :role => String.t,
    :role_name => String.t,
    :ship_type_id => integer(),
    :solar_system_id => integer(),
    :squad_id => integer(),
    :station_id => integer() | nil,
    :takes_fleet_warp => boolean(),
    :wing_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:join_time, :datetime, nil)
  end
end

