# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdLink do
  @moduledoc """
  link object
  """

  @derive Jason.Encoder
  defstruct [
    :destination_pin_id,
    :link_level,
    :source_pin_id
  ]

  @type t :: %__MODULE__{
    :destination_pin_id => integer(),
    :link_level => integer(),
    :source_pin_id => integer()
  }

  def decode(value) do
    value
  end
end

