# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetSovereigntyMap200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :corporation_id,
    :faction_id,
    :system_id
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :corporation_id => integer() | nil,
    :faction_id => integer() | nil,
    :system_id => integer()
  }

  def decode(value) do
    value
  end
end

