# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdAttributesOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :accrued_remap_cooldown_date,
    :bonus_remaps,
    :charisma,
    :intelligence,
    :last_remap_date,
    :memory,
    :perception,
    :willpower
  ]

  @type t :: %__MODULE__{
    :accrued_remap_cooldown_date => DateTime.t | nil,
    :bonus_remaps => integer() | nil,
    :charisma => integer(),
    :intelligence => integer(),
    :last_remap_date => DateTime.t | nil,
    :memory => integer(),
    :perception => integer(),
    :willpower => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:accrued_remap_cooldown_date, :datetime, nil)
     |> Deserializer.deserialize(:last_remap_date, :datetime, nil)
  end
end

