# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwStats200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :faction_id,
    :kills,
    :pilots,
    :systems_controlled,
    :victory_points
  ]

  @type t :: %__MODULE__{
    :faction_id => integer(),
    :kills => EveESI.Model.GetFwStatsKills.t,
    :pilots => integer(),
    :systems_controlled => integer(),
    :victory_points => EveESI.Model.GetFwStatsVictoryPoints.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:kills, :struct, EveESI.Model.GetFwStatsKills)
     |> Deserializer.deserialize(:victory_points, :struct, EveESI.Model.GetFwStatsVictoryPoints)
  end
end

