# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniversePlanetsPlanetIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :planet_id,
    :position,
    :system_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :planet_id => integer(),
    :position => EveESI.Model.GetUniversePlanetsPlanetIdPosition.t,
    :system_id => integer(),
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:position, :struct, EveESI.Model.GetUniversePlanetsPlanetIdPosition)
  end
end

