# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdContent do
  @moduledoc """
  content object
  """

  @derive Jason.Encoder
  defstruct [
    :amount,
    :type_id
  ]

  @type t :: %__MODULE__{
    :amount => integer(),
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

