# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseTypesTypeIdDogmaAttribute do
  @moduledoc """
  dogma_attribute object
  """

  @derive Jason.Encoder
  defstruct [
    :attribute_id,
    :value
  ]

  @type t :: %__MODULE__{
    :attribute_id => integer(),
    :value => float()
  }

  def decode(value) do
    value
  end
end

