# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdMailLabelsLabel do
  @moduledoc """
  label object
  """

  @derive Jason.Encoder
  defstruct [
    :color,
    :label_id,
    :name,
    :unread_count
  ]

  @type t :: %__MODULE__{
    :color => String.t | nil,
    :label_id => integer() | nil,
    :name => String.t | nil,
    :unread_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

