# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseSchematicsSchematicIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :cycle_time,
    :schematic_name
  ]

  @type t :: %__MODULE__{
    :cycle_time => integer(),
    :schematic_name => String.t
  }

  def decode(value) do
    value
  end
end

