# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseRaces200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :description,
    :name,
    :race_id
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer(),
    :description => String.t,
    :name => String.t,
    :race_id => integer()
  }

  def decode(value) do
    value
  end
end

