# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetDogmaAttributesAttributeIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :attribute_id,
    :default_value,
    :description,
    :display_name,
    :high_is_good,
    :icon_id,
    :name,
    :published,
    :stackable,
    :unit_id
  ]

  @type t :: %__MODULE__{
    :attribute_id => integer(),
    :default_value => float() | nil,
    :description => String.t | nil,
    :display_name => String.t | nil,
    :high_is_good => boolean() | nil,
    :icon_id => integer() | nil,
    :name => String.t | nil,
    :published => boolean() | nil,
    :stackable => boolean() | nil,
    :unit_id => integer() | nil
  }

  def decode(value) do
    value
  end
end

