# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwLeaderboardsKills do
  @moduledoc """
  Top 4 rankings of factions by number of kills from yesterday, last week and in total
  """

  @derive Jason.Encoder
  defstruct [
    :active_total,
    :last_week,
    :yesterday
  ]

  @type t :: %__MODULE__{
    :active_total => [EveESI.Model.GetFwLeaderboardsActiveTotalActiveTotal.t],
    :last_week => [EveESI.Model.GetFwLeaderboardsLastWeekLastWeek.t],
    :yesterday => [EveESI.Model.GetFwLeaderboardsYesterdayYesterday.t]
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:active_total, :list, EveESI.Model.GetFwLeaderboardsActiveTotalActiveTotal)
     |> Deserializer.deserialize(:last_week, :list, EveESI.Model.GetFwLeaderboardsLastWeekLastWeek)
     |> Deserializer.deserialize(:yesterday, :list, EveESI.Model.GetFwLeaderboardsYesterdayYesterday)
  end
end

