# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdRoute do
  @moduledoc """
  route object
  """

  @derive Jason.Encoder
  defstruct [
    :content_type_id,
    :destination_pin_id,
    :quantity,
    :route_id,
    :source_pin_id,
    :waypoints
  ]

  @type t :: %__MODULE__{
    :content_type_id => integer(),
    :destination_pin_id => integer(),
    :quantity => float(),
    :route_id => integer(),
    :source_pin_id => integer(),
    :waypoints => [integer()] | nil
  }

  def decode(value) do
    value
  end
end

