# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdWalletsDivisionJournal200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :amount,
    :balance,
    :context_id,
    :context_id_type,
    :date,
    :description,
    :first_party_id,
    :id,
    :reason,
    :ref_type,
    :second_party_id,
    :tax,
    :tax_receiver_id
  ]

  @type t :: %__MODULE__{
    :amount => float() | nil,
    :balance => float() | nil,
    :context_id => integer() | nil,
    :context_id_type => String.t | nil,
    :date => DateTime.t,
    :description => String.t,
    :first_party_id => integer() | nil,
    :id => integer(),
    :reason => String.t | nil,
    :ref_type => String.t,
    :second_party_id => integer() | nil,
    :tax => float() | nil,
    :tax_receiver_id => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date, :datetime, nil)
  end
end

