# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdCalendarEventIdAttendees200Ok do
  @moduledoc """
  character_id and response of an attendee
  """

  @derive Jason.Encoder
  defstruct [
    :character_id,
    :event_response
  ]

  @type t :: %__MODULE__{
    :character_id => integer() | nil,
    :event_response => String.t | nil
  }

  def decode(value) do
    value
  end
end

