# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetKillmailsKillmailIdKillmailHashItem do
  @moduledoc """
  item object
  """

  @derive Jason.Encoder
  defstruct [
    :flag,
    :item_type_id,
    :items,
    :quantity_destroyed,
    :quantity_dropped,
    :singleton
  ]

  @type t :: %__MODULE__{
    :flag => integer(),
    :item_type_id => integer(),
    :items => [EveESI.Model.GetKillmailsKillmailIdKillmailHashItemsItem.t] | nil,
    :quantity_destroyed => integer() | nil,
    :quantity_dropped => integer() | nil,
    :singleton => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, EveESI.Model.GetKillmailsKillmailIdKillmailHashItemsItem)
  end
end

