# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwSystems200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :contested,
    :occupier_faction_id,
    :owner_faction_id,
    :solar_system_id,
    :victory_points,
    :victory_points_threshold
  ]

  @type t :: %__MODULE__{
    :contested => String.t,
    :occupier_faction_id => integer(),
    :owner_faction_id => integer(),
    :solar_system_id => integer(),
    :victory_points => integer(),
    :victory_points_threshold => integer()
  }

  def decode(value) do
    value
  end
end

