# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdBookmarksFolders200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :creator_id,
    :folder_id,
    :name
  ]

  @type t :: %__MODULE__{
    :creator_id => integer() | nil,
    :folder_id => integer(),
    :name => String.t
  }

  def decode(value) do
    value
  end
end

