# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdSkillsOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :skills,
    :total_sp,
    :unallocated_sp
  ]

  @type t :: %__MODULE__{
    :skills => [EveESI.Model.GetCharactersCharacterIdSkillsSkill.t],
    :total_sp => integer(),
    :unallocated_sp => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:skills, :list, EveESI.Model.GetCharactersCharacterIdSkillsSkill)
  end
end

