# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdPin do
  @moduledoc """
  pin object
  """

  @derive Jason.Encoder
  defstruct [
    :contents,
    :expiry_time,
    :extractor_details,
    :factory_details,
    :install_time,
    :last_cycle_start,
    :latitude,
    :longitude,
    :pin_id,
    :schematic_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :contents => [EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdContent.t] | nil,
    :expiry_time => DateTime.t | nil,
    :extractor_details => EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails.t | nil,
    :factory_details => EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails.t | nil,
    :install_time => DateTime.t | nil,
    :last_cycle_start => DateTime.t | nil,
    :latitude => float(),
    :longitude => float(),
    :pin_id => integer(),
    :schematic_id => integer() | nil,
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contents, :list, EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdContent)
     |> Deserializer.deserialize(:expiry_time, :datetime, nil)
     |> Deserializer.deserialize(:extractor_details, :struct, EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails)
     |> Deserializer.deserialize(:factory_details, :struct, EveESI.Model.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails)
     |> Deserializer.deserialize(:install_time, :datetime, nil)
     |> Deserializer.deserialize(:last_cycle_start, :datetime, nil)
  end
end

