# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetSovereigntyStructures200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :solar_system_id,
    :structure_id,
    :structure_type_id,
    :vulnerability_occupancy_level,
    :vulnerable_end_time,
    :vulnerable_start_time
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer(),
    :solar_system_id => integer(),
    :structure_id => integer(),
    :structure_type_id => integer(),
    :vulnerability_occupancy_level => float() | nil,
    :vulnerable_end_time => DateTime.t | nil,
    :vulnerable_start_time => DateTime.t | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:vulnerable_end_time, :datetime, nil)
     |> Deserializer.deserialize(:vulnerable_start_time, :datetime, nil)
  end
end

