# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :birthday,
    :bloodline_id,
    :corporation_id,
    :description,
    :faction_id,
    :gender,
    :name,
    :race_id,
    :security_status,
    :title
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :birthday => DateTime.t,
    :bloodline_id => integer(),
    :corporation_id => integer(),
    :description => String.t | nil,
    :faction_id => integer() | nil,
    :gender => String.t,
    :name => String.t,
    :race_id => integer(),
    :security_status => float() | nil,
    :title => String.t | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:birthday, :datetime, nil)
  end
end

