# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdBookmarksItem do
  @moduledoc """
  Optional object that is returned if a bookmark was made on a particular item.
  """

  @derive Jason.Encoder
  defstruct [
    :item_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :item_id => integer(),
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

