# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetKillmailsKillmailIdKillmailHashVictim do
  @moduledoc """
  victim object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :character_id,
    :corporation_id,
    :damage_taken,
    :faction_id,
    :items,
    :position,
    :ship_type_id
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :character_id => integer() | nil,
    :corporation_id => integer() | nil,
    :damage_taken => integer(),
    :faction_id => integer() | nil,
    :items => [EveESI.Model.GetKillmailsKillmailIdKillmailHashItem.t] | nil,
    :position => EveESI.Model.GetKillmailsKillmailIdKillmailHashPosition.t | nil,
    :ship_type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, EveESI.Model.GetKillmailsKillmailIdKillmailHashItem)
     |> Deserializer.deserialize(:position, :struct, EveESI.Model.GetKillmailsKillmailIdKillmailHashPosition)
  end
end

