# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseSystemJumps200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :ship_jumps,
    :system_id
  ]

  @type t :: %__MODULE__{
    :ship_jumps => integer(),
    :system_id => integer()
  }

  def decode(value) do
    value
  end
end

