# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetKillmailsKillmailIdKillmailHashAttacker do
  @moduledoc """
  attacker object
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :character_id,
    :corporation_id,
    :damage_done,
    :faction_id,
    :final_blow,
    :security_status,
    :ship_type_id,
    :weapon_type_id
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :character_id => integer() | nil,
    :corporation_id => integer() | nil,
    :damage_done => integer(),
    :faction_id => integer() | nil,
    :final_blow => boolean(),
    :security_status => float(),
    :ship_type_id => integer() | nil,
    :weapon_type_id => integer() | nil
  }

  def decode(value) do
    value
  end
end

