# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdContractsContractIdItems200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :is_included,
    :is_singleton,
    :quantity,
    :raw_quantity,
    :record_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :is_included => boolean(),
    :is_singleton => boolean(),
    :quantity => integer(),
    :raw_quantity => integer() | nil,
    :record_id => integer(),
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

