# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFleetsFleetIdWings200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :squads
  ]

  @type t :: %__MODULE__{
    :id => integer(),
    :name => String.t,
    :squads => [EveESI.Model.GetFleetsFleetIdWingsSquad.t]
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:squads, :list, EveESI.Model.GetFleetsFleetIdWingsSquad)
  end
end

