# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdOrders200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :duration,
    :escrow,
    :is_buy_order,
    :issued,
    :issued_by,
    :location_id,
    :min_volume,
    :order_id,
    :price,
    :range,
    :region_id,
    :type_id,
    :volume_remain,
    :volume_total,
    :wallet_division
  ]

  @type t :: %__MODULE__{
    :duration => integer(),
    :escrow => float() | nil,
    :is_buy_order => boolean() | nil,
    :issued => DateTime.t,
    :issued_by => integer(),
    :location_id => integer(),
    :min_volume => integer() | nil,
    :order_id => integer(),
    :price => float(),
    :range => String.t,
    :region_id => integer(),
    :type_id => integer(),
    :volume_remain => integer(),
    :volume_total => integer(),
    :wallet_division => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:issued, :datetime, nil)
  end
end

