# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdFittings200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :fitting_id,
    :items,
    :name,
    :ship_type_id
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :fitting_id => integer(),
    :items => [EveESI.Model.GetCharactersCharacterIdFittingsItem.t],
    :name => String.t,
    :ship_type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, EveESI.Model.GetCharactersCharacterIdFittingsItem)
  end
end

