# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseStarsStarIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :age,
    :luminosity,
    :name,
    :radius,
    :solar_system_id,
    :spectral_class,
    :temperature,
    :type_id
  ]

  @type t :: %__MODULE__{
    :age => integer(),
    :luminosity => float(),
    :name => String.t,
    :radius => integer(),
    :solar_system_id => integer(),
    :spectral_class => String.t,
    :temperature => integer(),
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

