# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdClonesOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :home_location,
    :jump_clones,
    :last_clone_jump_date,
    :last_station_change_date
  ]

  @type t :: %__MODULE__{
    :home_location => EveESI.Model.GetCharactersCharacterIdClonesHomeLocation.t | nil,
    :jump_clones => [EveESI.Model.GetCharactersCharacterIdClonesJumpClone.t],
    :last_clone_jump_date => DateTime.t | nil,
    :last_station_change_date => DateTime.t | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:home_location, :struct, EveESI.Model.GetCharactersCharacterIdClonesHomeLocation)
     |> Deserializer.deserialize(:jump_clones, :list, EveESI.Model.GetCharactersCharacterIdClonesJumpClone)
     |> Deserializer.deserialize(:last_clone_jump_date, :datetime, nil)
     |> Deserializer.deserialize(:last_station_change_date, :datetime, nil)
  end
end

