# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdNotifications200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :is_read,
    :notification_id,
    :sender_id,
    :sender_type,
    :text,
    :timestamp,
    :type
  ]

  @type t :: %__MODULE__{
    :is_read => boolean() | nil,
    :notification_id => integer(),
    :sender_id => integer(),
    :sender_type => String.t,
    :text => String.t | nil,
    :timestamp => DateTime.t,
    :type => String.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end

