# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdSearchOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :agent,
    :alliance,
    :character,
    :constellation,
    :corporation,
    :faction,
    :inventory_type,
    :region,
    :solar_system,
    :station,
    :structure
  ]

  @type t :: %__MODULE__{
    :agent => [integer()] | nil,
    :alliance => [integer()] | nil,
    :character => [integer()] | nil,
    :constellation => [integer()] | nil,
    :corporation => [integer()] | nil,
    :faction => [integer()] | nil,
    :inventory_type => [integer()] | nil,
    :region => [integer()] | nil,
    :solar_system => [integer()] | nil,
    :station => [integer()] | nil,
    :structure => [integer()] | nil
  }

  def decode(value) do
    value
  end
end

