# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdCalendar200Ok do
  @moduledoc """
  event
  """

  @derive Jason.Encoder
  defstruct [
    :event_date,
    :event_id,
    :event_response,
    :importance,
    :title
  ]

  @type t :: %__MODULE__{
    :event_date => DateTime.t | nil,
    :event_id => integer() | nil,
    :event_response => String.t | nil,
    :importance => integer() | nil,
    :title => String.t | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:event_date, :datetime, nil)
  end
end

