# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetDogmaEffectsEffectIdModifier do
  @moduledoc """
  modifier object
  """

  @derive Jason.Encoder
  defstruct [
    :domain,
    :effect_id,
    :func,
    :modified_attribute_id,
    :modifying_attribute_id,
    :operator
  ]

  @type t :: %__MODULE__{
    :domain => String.t | nil,
    :effect_id => integer() | nil,
    :func => String.t,
    :modified_attribute_id => integer() | nil,
    :modifying_attribute_id => integer() | nil,
    :operator => integer() | nil
  }

  def decode(value) do
    value
  end
end

