# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFleetsFleetIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :is_free_move,
    :is_registered,
    :is_voice_enabled,
    :motd
  ]

  @type t :: %__MODULE__{
    :is_free_move => boolean(),
    :is_registered => boolean(),
    :is_voice_enabled => boolean(),
    :motd => String.t
  }

  def decode(value) do
    value
  end
end

