# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdRolesHistory200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :changed_at,
    :character_id,
    :issuer_id,
    :new_roles,
    :old_roles,
    :role_type
  ]

  @type t :: %__MODULE__{
    :changed_at => DateTime.t,
    :character_id => integer(),
    :issuer_id => integer(),
    :new_roles => [String.t],
    :old_roles => [String.t],
    :role_type => String.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:changed_at, :datetime, nil)
  end
end

