# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetAlliancesAllianceIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :creator_corporation_id,
    :creator_id,
    :date_founded,
    :executor_corporation_id,
    :faction_id,
    :name,
    :ticker
  ]

  @type t :: %__MODULE__{
    :creator_corporation_id => integer(),
    :creator_id => integer(),
    :date_founded => DateTime.t,
    :executor_corporation_id => integer() | nil,
    :faction_id => integer() | nil,
    :name => String.t,
    :ticker => String.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date_founded, :datetime, nil)
  end
end

