# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdFwStatsOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :enlisted_on,
    :faction_id,
    :kills,
    :pilots,
    :victory_points
  ]

  @type t :: %__MODULE__{
    :enlisted_on => DateTime.t | nil,
    :faction_id => integer() | nil,
    :kills => EveESI.Model.GetCorporationsCorporationIdFwStatsKills.t,
    :pilots => integer() | nil,
    :victory_points => EveESI.Model.GetCorporationsCorporationIdFwStatsVictoryPoints.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:enlisted_on, :datetime, nil)
     |> Deserializer.deserialize(:kills, :struct, EveESI.Model.GetCorporationsCorporationIdFwStatsKills)
     |> Deserializer.deserialize(:victory_points, :struct, EveESI.Model.GetCorporationsCorporationIdFwStatsVictoryPoints)
  end
end

