# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetLoyaltyStoresCorporationIdOffers200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :ak_cost,
    :isk_cost,
    :lp_cost,
    :offer_id,
    :quantity,
    :required_items,
    :type_id
  ]

  @type t :: %__MODULE__{
    :ak_cost => integer() | nil,
    :isk_cost => integer(),
    :lp_cost => integer(),
    :offer_id => integer(),
    :quantity => integer(),
    :required_items => [EveESI.Model.GetLoyaltyStoresCorporationIdOffersRequiredItem.t],
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:required_items, :list, EveESI.Model.GetLoyaltyStoresCorporationIdOffersRequiredItem)
  end
end

