# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdAgentsResearch200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :agent_id,
    :points_per_day,
    :remainder_points,
    :skill_type_id,
    :started_at
  ]

  @type t :: %__MODULE__{
    :agent_id => integer(),
    :points_per_day => float(),
    :remainder_points => float(),
    :skill_type_id => integer(),
    :started_at => DateTime.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:started_at, :datetime, nil)
  end
end

