# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwLeaderboardsCharactersKills do
  @moduledoc """
  Top 100 rankings of pilots by number of kills from yesterday, last week and in total
  """

  @derive Jason.Encoder
  defstruct [
    :active_total,
    :last_week,
    :yesterday
  ]

  @type t :: %__MODULE__{
    :active_total => [EveESI.Model.GetFwLeaderboardsCharactersActiveTotalActiveTotal.t],
    :last_week => [EveESI.Model.GetFwLeaderboardsCharactersLastWeekLastWeek.t],
    :yesterday => [EveESI.Model.GetFwLeaderboardsCharactersYesterdayYesterday.t]
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:active_total, :list, EveESI.Model.GetFwLeaderboardsCharactersActiveTotalActiveTotal)
     |> Deserializer.deserialize(:last_week, :list, EveESI.Model.GetFwLeaderboardsCharactersLastWeekLastWeek)
     |> Deserializer.deserialize(:yesterday, :list, EveESI.Model.GetFwLeaderboardsCharactersYesterdayYesterday)
  end
end

