# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetMarketsGroupsMarketGroupIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :market_group_id,
    :name,
    :parent_group_id,
    :types
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :market_group_id => integer(),
    :name => String.t,
    :parent_group_id => integer() | nil,
    :types => [integer()]
  }

  def decode(value) do
    value
  end
end

