# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdBookmarksCoordinates do
  @moduledoc """
  Optional object that is returned if a bookmark was made on a planet or a random location in space.
  """

  @derive Jason.Encoder
  defstruct [
    :x,
    :y,
    :z
  ]

  @type t :: %__MODULE__{
    :x => float(),
    :y => float(),
    :z => float()
  }

  def decode(value) do
    value
  end
end

