# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdMedalsIssued200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :character_id,
    :issued_at,
    :issuer_id,
    :medal_id,
    :reason,
    :status
  ]

  @type t :: %__MODULE__{
    :character_id => integer(),
    :issued_at => DateTime.t,
    :issuer_id => integer(),
    :medal_id => integer(),
    :reason => String.t,
    :status => String.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:issued_at, :datetime, nil)
  end
end

