# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseFactions200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :corporation_id,
    :description,
    :faction_id,
    :is_unique,
    :militia_corporation_id,
    :name,
    :size_factor,
    :solar_system_id,
    :station_count,
    :station_system_count
  ]

  @type t :: %__MODULE__{
    :corporation_id => integer() | nil,
    :description => String.t,
    :faction_id => integer(),
    :is_unique => boolean(),
    :militia_corporation_id => integer() | nil,
    :name => String.t,
    :size_factor => float(),
    :solar_system_id => integer() | nil,
    :station_count => integer(),
    :station_system_count => integer()
  }

  def decode(value) do
    value
  end
end

