# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetWarsWarIdDefender do
  @moduledoc """
  The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id
  """

  @derive Jason.Encoder
  defstruct [
    :alliance_id,
    :corporation_id,
    :isk_destroyed,
    :ships_killed
  ]

  @type t :: %__MODULE__{
    :alliance_id => integer() | nil,
    :corporation_id => integer() | nil,
    :isk_destroyed => float(),
    :ships_killed => integer()
  }

  def decode(value) do
    value
  end
end

