# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdWalletsDivisionTransactions200Ok do
  @moduledoc """
  wallet transaction
  """

  @derive Jason.Encoder
  defstruct [
    :client_id,
    :date,
    :is_buy,
    :journal_ref_id,
    :location_id,
    :quantity,
    :transaction_id,
    :type_id,
    :unit_price
  ]

  @type t :: %__MODULE__{
    :client_id => integer(),
    :date => DateTime.t,
    :is_buy => boolean(),
    :journal_ref_id => integer(),
    :location_id => integer(),
    :quantity => integer(),
    :transaction_id => integer(),
    :type_id => integer(),
    :unit_price => float()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date, :datetime, nil)
  end
end

