# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseStargatesStargateIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :destination,
    :name,
    :position,
    :stargate_id,
    :system_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :destination => EveESI.Model.GetUniverseStargatesStargateIdDestination.t,
    :name => String.t,
    :position => EveESI.Model.GetUniverseStargatesStargateIdPosition.t,
    :stargate_id => integer(),
    :system_id => integer(),
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:destination, :struct, EveESI.Model.GetUniverseStargatesStargateIdDestination)
     |> Deserializer.deserialize(:position, :struct, EveESI.Model.GetUniverseStargatesStargateIdPosition)
  end
end

