# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetInsurancePrices200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :levels,
    :type_id
  ]

  @type t :: %__MODULE__{
    :levels => [EveESI.Model.GetInsurancePricesLevel.t],
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:levels, :list, EveESI.Model.GetInsurancePricesLevel)
  end
end

