# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetIndustrySystems200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :cost_indices,
    :solar_system_id
  ]

  @type t :: %__MODULE__{
    :cost_indices => [EveESI.Model.GetIndustrySystemsCostIndice.t],
    :solar_system_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cost_indices, :list, EveESI.Model.GetIndustrySystemsCostIndice)
  end
end

