# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdPlanets200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :last_update,
    :num_pins,
    :owner_id,
    :planet_id,
    :planet_type,
    :solar_system_id,
    :upgrade_level
  ]

  @type t :: %__MODULE__{
    :last_update => DateTime.t,
    :num_pins => integer(),
    :owner_id => integer(),
    :planet_id => integer(),
    :planet_type => String.t,
    :solar_system_id => integer(),
    :upgrade_level => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:last_update, :datetime, nil)
  end
end

