# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseSystemKills200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :npc_kills,
    :pod_kills,
    :ship_kills,
    :system_id
  ]

  @type t :: %__MODULE__{
    :npc_kills => integer(),
    :pod_kills => integer(),
    :ship_kills => integer(),
    :system_id => integer()
  }

  def decode(value) do
    value
  end
end

