# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetDogmaEffectsEffectIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :disallow_auto_repeat,
    :discharge_attribute_id,
    :display_name,
    :duration_attribute_id,
    :effect_category,
    :effect_id,
    :electronic_chance,
    :falloff_attribute_id,
    :icon_id,
    :is_assistance,
    :is_offensive,
    :is_warp_safe,
    :modifiers,
    :name,
    :post_expression,
    :pre_expression,
    :published,
    :range_attribute_id,
    :range_chance,
    :tracking_speed_attribute_id
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :disallow_auto_repeat => boolean() | nil,
    :discharge_attribute_id => integer() | nil,
    :display_name => String.t | nil,
    :duration_attribute_id => integer() | nil,
    :effect_category => integer() | nil,
    :effect_id => integer(),
    :electronic_chance => boolean() | nil,
    :falloff_attribute_id => integer() | nil,
    :icon_id => integer() | nil,
    :is_assistance => boolean() | nil,
    :is_offensive => boolean() | nil,
    :is_warp_safe => boolean() | nil,
    :modifiers => [EveESI.Model.GetDogmaEffectsEffectIdModifier.t] | nil,
    :name => String.t | nil,
    :post_expression => integer() | nil,
    :pre_expression => integer() | nil,
    :published => boolean() | nil,
    :range_attribute_id => integer() | nil,
    :range_chance => boolean() | nil,
    :tracking_speed_attribute_id => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:modifiers, :list, EveESI.Model.GetDogmaEffectsEffectIdModifier)
  end
end

