# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdCorporationhistory200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :corporation_id,
    :is_deleted,
    :record_id,
    :start_date
  ]

  @type t :: %__MODULE__{
    :corporation_id => integer(),
    :is_deleted => boolean() | nil,
    :record_id => integer(),
    :start_date => DateTime.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:start_date, :datetime, nil)
  end
end

