# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseStructuresStructureIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :owner_id,
    :position,
    :solar_system_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :owner_id => integer(),
    :position => EveESI.Model.GetUniverseStructuresStructureIdPosition.t | nil,
    :solar_system_id => integer(),
    :type_id => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:position, :struct, EveESI.Model.GetUniverseStructuresStructureIdPosition)
  end
end

