# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwLeaderboardsCharactersLastWeekLastWeek do
  @moduledoc """
  last_week object
  """

  @derive Jason.Encoder
  defstruct [
    :amount,
    :character_id
  ]

  @type t :: %__MODULE__{
    :amount => integer() | nil,
    :character_id => integer() | nil
  }

  def decode(value) do
    value
  end
end

