# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdMailLabelsOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :labels,
    :total_unread_count
  ]

  @type t :: %__MODULE__{
    :labels => [EveESI.Model.GetCharactersCharacterIdMailLabelsLabel.t] | nil,
    :total_unread_count => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:labels, :list, EveESI.Model.GetCharactersCharacterIdMailLabelsLabel)
  end
end

