# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdMailMailIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :body,
    :from,
    :labels,
    :read,
    :recipients,
    :subject,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :body => String.t | nil,
    :from => integer() | nil,
    :labels => [integer()] | nil,
    :read => boolean() | nil,
    :recipients => [EveESI.Model.GetCharactersCharacterIdMailMailIdRecipient.t] | nil,
    :subject => String.t | nil,
    :timestamp => DateTime.t | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:recipients, :list, EveESI.Model.GetCharactersCharacterIdMailMailIdRecipient)
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end

