# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseStargatesStargateIdDestination do
  @moduledoc """
  destination object
  """

  @derive Jason.Encoder
  defstruct [
    :stargate_id,
    :system_id
  ]

  @type t :: %__MODULE__{
    :stargate_id => integer(),
    :system_id => integer()
  }

  def decode(value) do
    value
  end
end

