# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetIndustryFacilities200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :facility_id,
    :owner_id,
    :region_id,
    :solar_system_id,
    :tax,
    :type_id
  ]

  @type t :: %__MODULE__{
    :facility_id => integer(),
    :owner_id => integer(),
    :region_id => integer(),
    :solar_system_id => integer(),
    :tax => float() | nil,
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

