# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetKillmailsKillmailIdKillmailHashOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :attackers,
    :killmail_id,
    :killmail_time,
    :moon_id,
    :solar_system_id,
    :victim,
    :war_id
  ]

  @type t :: %__MODULE__{
    :attackers => [EveESI.Model.GetKillmailsKillmailIdKillmailHashAttacker.t],
    :killmail_id => integer(),
    :killmail_time => DateTime.t,
    :moon_id => integer() | nil,
    :solar_system_id => integer(),
    :victim => EveESI.Model.GetKillmailsKillmailIdKillmailHashVictim.t,
    :war_id => integer() | nil
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:attackers, :list, EveESI.Model.GetKillmailsKillmailIdKillmailHashAttacker)
     |> Deserializer.deserialize(:killmail_time, :datetime, nil)
     |> Deserializer.deserialize(:victim, :struct, EveESI.Model.GetKillmailsKillmailIdKillmailHashVictim)
  end
end

