# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationsCorporationIdStructuresService do
  @moduledoc """
  service object
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :state
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :state => String.t
  }

  def decode(value) do
    value
  end
end

