# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwStatsVictoryPoints do
  @moduledoc """
  Summary of victory points gained for the given faction
  """

  @derive Jason.Encoder
  defstruct [
    :last_week,
    :total,
    :yesterday
  ]

  @type t :: %__MODULE__{
    :last_week => integer(),
    :total => integer(),
    :yesterday => integer()
  }

  def decode(value) do
    value
  end
end

