# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetMarketsPrices200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :adjusted_price,
    :average_price,
    :type_id
  ]

  @type t :: %__MODULE__{
    :adjusted_price => float() | nil,
    :average_price => float() | nil,
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

