# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdMedalsGraphic do
  @moduledoc """
  graphic object
  """

  @derive Jason.Encoder
  defstruct [
    :color,
    :graphic,
    :layer,
    :part
  ]

  @type t :: %__MODULE__{
    :color => integer() | nil,
    :graphic => String.t,
    :layer => integer(),
    :part => integer()
  }

  def decode(value) do
    value
  end
end

