# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdLocationOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :solar_system_id,
    :station_id,
    :structure_id
  ]

  @type t :: %__MODULE__{
    :solar_system_id => integer(),
    :station_id => integer() | nil,
    :structure_id => integer() | nil
  }

  def decode(value) do
    value
  end
end

