# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseBloodlines200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :bloodline_id,
    :charisma,
    :corporation_id,
    :description,
    :intelligence,
    :memory,
    :name,
    :perception,
    :race_id,
    :ship_type_id,
    :willpower
  ]

  @type t :: %__MODULE__{
    :bloodline_id => integer(),
    :charisma => integer(),
    :corporation_id => integer(),
    :description => String.t,
    :intelligence => integer(),
    :memory => integer(),
    :name => String.t,
    :perception => integer(),
    :race_id => integer(),
    :ship_type_id => integer() | nil,
    :willpower => integer()
  }

  def decode(value) do
    value
  end
end

