# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCorporationCorporationIdMiningObservers200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :last_updated,
    :observer_id,
    :observer_type
  ]

  @type t :: %__MODULE__{
    :last_updated => Date.t,
    :observer_id => integer(),
    :observer_type => String.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:last_updated, :date, nil)
  end
end

