# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetCharactersCharacterIdMining200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :date,
    :quantity,
    :solar_system_id,
    :type_id
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :quantity => integer(),
    :solar_system_id => integer(),
    :type_id => integer()
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date, :date, nil)
  end
end

