# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetFwLeaderboardsOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :kills,
    :victory_points
  ]

  @type t :: %__MODULE__{
    :kills => EveESI.Model.GetFwLeaderboardsKills.t,
    :victory_points => EveESI.Model.GetFwLeaderboardsVictoryPoints.t
  }

  alias EveESI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:kills, :struct, EveESI.Model.GetFwLeaderboardsKills)
     |> Deserializer.deserialize(:victory_points, :struct, EveESI.Model.GetFwLeaderboardsVictoryPoints)
  end
end

