# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetIncursions200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :constellation_id,
    :faction_id,
    :has_boss,
    :infested_solar_systems,
    :influence,
    :staging_solar_system_id,
    :state,
    :type
  ]

  @type t :: %__MODULE__{
    :constellation_id => integer(),
    :faction_id => integer(),
    :has_boss => boolean(),
    :infested_solar_systems => [integer()],
    :influence => float(),
    :staging_solar_system_id => integer(),
    :state => String.t,
    :type => String.t
  }

  def decode(value) do
    value
  end
end

