# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetContractsPublicItemsContractId200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :is_blueprint_copy,
    :is_included,
    :item_id,
    :material_efficiency,
    :quantity,
    :record_id,
    :runs,
    :time_efficiency,
    :type_id
  ]

  @type t :: %__MODULE__{
    :is_blueprint_copy => boolean() | nil,
    :is_included => boolean(),
    :item_id => integer() | nil,
    :material_efficiency => integer() | nil,
    :quantity => integer(),
    :record_id => integer(),
    :runs => integer() | nil,
    :time_efficiency => integer() | nil,
    :type_id => integer()
  }

  def decode(value) do
    value
  end
end

