# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.GetUniverseGroupsGroupIdOk do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :category_id,
    :group_id,
    :name,
    :published,
    :types
  ]

  @type t :: %__MODULE__{
    :category_id => integer(),
    :group_id => integer(),
    :name => String.t,
    :published => boolean(),
    :types => [integer()]
  }

  def decode(value) do
    value
  end
end

