# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.PostUniverseNames200Ok do
  @moduledoc """
  200 ok object
  """

  @derive Jason.Encoder
  defstruct [
    :category,
    :id,
    :name
  ]

  @type t :: %__MODULE__{
    :category => String.t,
    :id => integer(),
    :name => String.t
  }

  def decode(value) do
    value
  end
end

