# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.PutFleetsFleetIdNewSettings do
  @moduledoc """
  new_settings object
  """

  @derive Jason.Encoder
  defstruct [
    :is_free_move,
    :motd
  ]

  @type t :: %__MODULE__{
    :is_free_move => boolean() | nil,
    :motd => String.t | nil
  }

  def decode(value) do
    value
  end
end

