# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.PutCharactersCharacterIdMailMailIdContents do
  @moduledoc """
  contents object
  """

  @derive Jason.Encoder
  defstruct [
    :labels,
    :read
  ]

  @type t :: %__MODULE__{
    :labels => [integer()] | nil,
    :read => boolean() | nil
  }

  def decode(value) do
    value
  end
end

