# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.PutCharactersCharacterIdCalendarEventIdResponse do
  @moduledoc """
  response object
  """

  @derive Jason.Encoder
  defstruct [
    :response
  ]

  @type t :: %__MODULE__{
    :response => String.t
  }

  def decode(value) do
    value
  end
end

