# NOTE: This file is auto generated by OpenAPI Generator 7.11.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule EveESI.Model.ServiceUnavailable do
  @moduledoc """
  Service unavailable model
  """

  @derive Jason.Encoder
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => String.t
  }

  def decode(value) do
    value
  end
end

